In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
import pandas as pd

df1 = pd.read_csv("/content/drive/MyDrive/2026-Summer/IDXExchange-Intern/data/CRMLSSold202505.csv")
df2 = pd.read_csv("/content/drive/MyDrive/2026-Summer/IDXExchange-Intern/data/CRMLSSold202506.csv")
df3 = pd.read_csv("/content/drive/MyDrive/2026-Summer/IDXExchange-Intern/data/CRMLSSold202507.csv")
df4 = pd.read_csv("/content/drive/MyDrive/2026-Summer/IDXExchange-Intern/data/CRMLSSold202508.csv")
df5 = pd.read_csv("/content/drive/MyDrive/2026-Summer/IDXExchange-Intern/data/CRMLSSold202509.csv")
df6 = pd.read_csv("/content/drive/MyDrive/2026-Summer/IDXExchange-Intern/data/CRMLSSold202510.csv")
df7 = pd.read_csv("/content/drive/MyDrive/2026-Summer/IDXExchange-Intern/data/CRMLSSold202511.csv")
df8 = pd.read_csv("/content/drive/MyDrive/2026-Summer/IDXExchange-Intern/data/CRMLSSold202512.csv")
df9 = pd.read_csv("/content/drive/MyDrive/2026-Summer/IDXExchange-Intern/data/CRMLSSold202601.csv")
df10 = pd.read_csv("/content/drive/MyDrive/2026-Summer/IDXExchange-Intern/data/CRMLSSold202602.csv")
df11 = pd.read_csv("/content/drive/MyDrive/2026-Summer/IDXExchange-Intern/data/CRMLSSold202603.csv")
df12 = pd.read_csv("/content/drive/MyDrive/2026-Summer/IDXExchange-Intern/data/CRMLSSold202604.csv")
df13 = pd.read_csv("/content/drive/MyDrive/2026-Summer/IDXExchange-Intern/data/CRMLSSold202605.csv")

/tmp/ipykernel_13357/3312040348.py:4: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv("/content/drive/MyDrive/2026-Summer/IDXExchange-Intern/data/CRMLSSold202506.csv")
/tmp/ipykernel_13357/3312040348.py:11: DtypeWarning: Columns (4,74) have mixed types. Specify dtype option on import or set low_memory=False.
  df9 = pd.read_csv("/content/drive/MyDrive/2026-Summer/IDXExchange-Intern/data/CRMLSSold202601.csv")

In [4]:
df_original = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12, df13], ignore_index=True)
df = df_original.copy()

In [5]:
df_sf = df[
    (df["PropertyType"] == "Residential") &
    (df["PropertySubType"] == "SingleFamilyResidence")
].copy()

In [6]:
financial_features = [
    "ListPrice",
    "OriginalListPrice",
    "ClosePrice",
    "TaxAnnualAmount",
    "TaxYear",
    "AssociationFee",
    "AssociationFeeFrequency",
    "LotSizeAcres",
    "LotSizeArea",
    "LotSizeSquareFeet",
    "LotSizeDimensions"
]

In [7]:
df_sf[financial_features].info()

<class 'pandas.core.frame.DataFrame'>
Index: 141997 entries, 8 to 281819
Data columns (total 11 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   ListPrice                141997 non-null  float64
 1   OriginalListPrice        141701 non-null  float64
 2   ClosePrice               141997 non-null  float64
 3   TaxAnnualAmount          0 non-null       float64
 4   TaxYear                  0 non-null       float64
 5   AssociationFee           100633 non-null  float64
 6   AssociationFeeFrequency  36144 non-null   object
 7   LotSizeAcres             139563 non-null  float64
 8   LotSizeArea              139577 non-null  float64
 9   LotSizeSquareFeet        139564 non-null  float64
 10  LotSizeDimensions        8990 non-null    object
dtypes: float64(9), object(2)
memory usage: 13.0+ MB

# **Handle missing values**

In [15]:
missing = pd.DataFrame({
    "Missing Count": df_sf[financial_features].isna().sum(),
    "Missing %": (
        df_sf[financial_features]
        .isna()
        .mean()*100
    ).round(2)
}).sort_values(by="Missing %", ascending=False)

missing

                   Missing Count  Missing %
ListPrice                      0        0.0
OriginalListPrice              0        0.0
ClosePrice                     0        0.0
AssociationFee                 0        0.0
LotSizeAcres                   0        0.0
LotSizeArea                    0        0.0
LotSizeSquareFeet              0        0.0

In [9]:
df_sf = df_sf.drop(columns=['TaxAnnualAmount', 'TaxYear', 'LotSizeDimensions', 'AssociationFeeFrequency'])

df_sf

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,Levels,LotSizeArea,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict
8,PacificWest,PacificWest,NaN,True,NaN,NaN,False,1800000.0,1114761060,realtorjinheechoi@hotmail.com,...,Two,7740.00,1.0,False,3.0,Fullerton Joint Union High,92833,310.0,7740.0,NaN
9,Malibu,Malibu,"Tile,Wood",True,NaN,True,False,1200000.0,1114760473,sonia@maisonrealestate.com,...,One,4697.00,NaN,False,2.0,NaN,90065,NaN,4697.0,NaN
12,Mlslistings,Mlslistings,"Carpet,Laminate",False,NaN,NaN,NaN,NaN,1114744790,dthurro@thurrorealty.com,...,NaN,5775.00,NaN,False,1.0,Other,95014,NaN,5775.0,NaN
13,OrangeCounty,OrangeCounty,NaN,True,NaN,NaN,False,1425000.0,1114743101,apreston@grandavenueca.com,...,One,7500.00,3.0,False,2.0,Placentia-Yorba Linda Unified,92886,124.0,7500.0,NaN
14,SanDiego,SanDiego,NaN,False,NaN,NaN,False,660000.0,1114741523,dave.advent@yahoo.com,...,Two,4552.00,NaN,False,2.0,NaN,92026,NaN,4552.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
281789,PacificWest,PacificWest,NaN,False,NaN,NaN,False,800000.0,1065799115,khwjenterprise@gmail.com,...,One,2921.00,2.0,False,0.0,Long Beach Unified,90813,0.0,2921.0,NaN
281791,NaN,VenturaCoastal,Wood,True,NaN,NaN,False,3500000.0,1063517703,ggoodmanrealty@aol.com,...,One,71.57,NaN,False,2.0,NaN,93060,NaN,3117589.2,NaN
281799,Southland,Southland,Wood,True,NaN,NaN,False,675000.0,1052367803,miguelcastellanosrealtor@gmail.com,...,One,7039.00,3.0,False,2.0,Los Angeles Unified,91345,0.0,7039.0,NaN
281801,ContraCosta,ContraCosta,"Carpet,SeeRemarks,Stone,Wood",NaN,NaN,True,False,35000000.0,1048618285,taso@ggsir.com,...,ThreeOrMore,935669.00,NaN,False,24.0,NaN,94507,3039.0,935669.0,NaN
281819,RanchoSoutheast,RanchoSoutheast,NaN,False,NaN,NaN,False,369000.0,497817474,roylman@aol.com,...,One,5202.00,2.0,False,0.0,Los Angeles Unified,90003,0.0,5202.0,NaN

## **Notes**

**TaxAnnualAmount** and **TaxYear** were dropped because both variables contained 100% missing values, providing no usable information for preprocessing or modeling. **LotSizeDimensions** and **AssociationFeeFrequency** were also dropped because they also had extremely high missing rates (93.67% and 74.55%, respectively).

In [10]:
fill_cols = ['AssociationFee', 'LotSizeSquareFeet', 'LotSizeAcres', 'LotSizeArea', 'OriginalListPrice']

for col in fill_cols:
  df_sf[col] = df_sf[col].fillna(df_sf[col].median())

## **Notes**

Missing values in **AssociationFee, LotSizeSquareFeet, LotSizeAcres, LotSizeArea, and OriginalListPrice** were imputed using the median because these variables are numerical and have outliers. **ListPrice** and **ClosePrice** were kept without modification because they didn't contain any missing values.

In [11]:
# Checking missing values

df_sf[["AssociationFee", "LotSizeSquareFeet", "LotSizeAcres", "LotSizeArea", "OriginalListPrice"]].isna().sum()

AssociationFee       0
LotSizeSquareFeet    0
LotSizeAcres         0
LotSizeArea          0
OriginalListPrice    0
dtype: int64

In [12]:
df_sf

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,Levels,LotSizeArea,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict
8,PacificWest,PacificWest,NaN,True,NaN,NaN,False,1800000.0,1114761060,realtorjinheechoi@hotmail.com,...,Two,7740.00,1.0,False,3.0,Fullerton Joint Union High,92833,310.0,7740.0,NaN
9,Malibu,Malibu,"Tile,Wood",True,NaN,True,False,1200000.0,1114760473,sonia@maisonrealestate.com,...,One,4697.00,NaN,False,2.0,NaN,90065,0.0,4697.0,NaN
12,Mlslistings,Mlslistings,"Carpet,Laminate",False,NaN,NaN,NaN,899000.0,1114744790,dthurro@thurrorealty.com,...,NaN,5775.00,NaN,False,1.0,Other,95014,0.0,5775.0,NaN
13,OrangeCounty,OrangeCounty,NaN,True,NaN,NaN,False,1425000.0,1114743101,apreston@grandavenueca.com,...,One,7500.00,3.0,False,2.0,Placentia-Yorba Linda Unified,92886,124.0,7500.0,NaN
14,SanDiego,SanDiego,NaN,False,NaN,NaN,False,660000.0,1114741523,dave.advent@yahoo.com,...,Two,4552.00,NaN,False,2.0,NaN,92026,0.0,4552.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
281789,PacificWest,PacificWest,NaN,False,NaN,NaN,False,800000.0,1065799115,khwjenterprise@gmail.com,...,One,2921.00,2.0,False,0.0,Long Beach Unified,90813,0.0,2921.0,NaN
281791,NaN,VenturaCoastal,Wood,True,NaN,NaN,False,3500000.0,1063517703,ggoodmanrealty@aol.com,...,One,71.57,NaN,False,2.0,NaN,93060,0.0,3117589.2,NaN
281799,Southland,Southland,Wood,True,NaN,NaN,False,675000.0,1052367803,miguelcastellanosrealtor@gmail.com,...,One,7039.00,3.0,False,2.0,Los Angeles Unified,91345,0.0,7039.0,NaN
281801,ContraCosta,ContraCosta,"Carpet,SeeRemarks,Stone,Wood",NaN,NaN,True,False,35000000.0,1048618285,taso@ggsir.com,...,ThreeOrMore,935669.00,NaN,False,24.0,NaN,94507,3039.0,935669.0,NaN
281819,RanchoSoutheast,RanchoSoutheast,NaN,False,NaN,NaN,False,369000.0,497817474,roylman@aol.com,...,One,5202.00,2.0,False,0.0,Los Angeles Unified,90003,0.0,5202.0,NaN

# **Convert categorical fields to numeric (Encoding)**

In [13]:
financial_features = [
    col for col in financial_features
    if col in df_sf.columns
]

df_sf[financial_features].info()

<class 'pandas.core.frame.DataFrame'>
Index: 141997 entries, 8 to 281819
Data columns (total 7 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   ListPrice          141997 non-null  float64
 1   OriginalListPrice  141997 non-null  float64
 2   ClosePrice         141997 non-null  float64
 3   AssociationFee     141997 non-null  float64
 4   LotSizeAcres       141997 non-null  float64
 5   LotSizeArea        141997 non-null  float64
 6   LotSizeSquareFeet  141997 non-null  float64
dtypes: float64(7)
memory usage: 8.7 MB

## **Notes**

After removing **AssociationFeeFrequency** and **LotSizeDimensions**, which are the only categorical variables in the financial features, there were no categorical variables in the group. Therefore, no encoding was required.

# **Normalize numerical features if needed**

Numerical features were not normalized at this stage because the final modeling approach has not been selected yet.

# **Create train/test split**

Use the most recent month of available data as the test set,
and the X months immediately preceding it as the training set. X is not fixed —
treat the training window length as a tunable choice and experiment to determine
the optimal value of X

In [17]:
df_sf["CloseDate"].dtype

dtype('O')

In [18]:
df_sf["CloseDate"] = pd.to_datetime(df_sf["CloseDate"])

In [24]:
test_df = df_sf[
    df_sf["CloseDate"].dt.to_period("M") == "2026-05"
]

train_df = df_sf[
    (df_sf["CloseDate"] >= "2025-05-01") &
    (df_sf["CloseDate"] < "2026-05-01")
]

print("Train set:", train_df.shape)
print("Test set:", test_df.shape)

Train set: (129973, 74)
Test set: (12024, 74)

## **Notes**

The most recent month (May 2026) was used as the test set, and the preceding 12 months (May 2025 to April 2026) were used as the training set. Different training window lengths (e.g., 6, 9, and 12 months) will be evaluated during the baseline modeling stage in Week 4 to determine the optimal value of X.